server:
  port: 9001

spring:
  application:
    name: cloudAlibabaPayment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8088
        port: 8719


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.112.58:3306/useForSpringCloud?useSSL=false
    username: root
    password: 4583900182886704565L
  profiles:
    active: